### ISSUE TITLE
weights.h5

### ISSUE THREAD

**Issue by drewgash** [bartchr808/EmotionPredictingCNN#1]
Hi Bart,

Great repository. You explain it like you actually want people to learn :)

One question, is a weights.h5 missing or we're supposed to create our own?

**Comment by bartchr808** [comment]
Hi Andrew,

Thanks for the comments! Regarding `weights.h5`, since Github has a [strict policy](https://help.github.com/articles/working-with-large-files/) regarding large file sizes, I'm unable to upload the CNN weights that I created (they are a ~2.3GB file). As such, you should train the model yourself in order to create your own weights.

**Comment by drewgash** [comment]
Noted. Pardon my "noobness" but how do I go about this? Isn't it supposed to be generated when I run the model.py file. This is what I get...

```
Traceback (most recent call last):
  File "model/model.py", line 56, in <module>
    model = model('weights.h5') # my weights
  File "model/model.py", line 50, in model
    model.load_weights(weights)
  File "C:\Users\drewgash\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\engine\network.py", line 1152, in load_weights
    with h5py.File(filepath, mode='r') as f:
  File "C:\Users\drewgash\AppData\Local\Programs\Python\Python35\lib\site-packages\h5py\_hl\files.py", line 313, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "C:\Users\drewgash\AppData\Local\Programs\Python\Python35\lib\site-packages\h5py\_hl\files.py", line 143, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'weights.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```

**Comment by bartchr808** [comment]
```
File "model/model.py", line 56, in <module>
    model = model('weights.h5') # my weights
```
This is saying that you want to load your model based on the weights in the file `weights.h5`. However, since you don't have that file, you will need to train your model from scratch. So you will need to replace line 56 with `model = model()`

The function `model` has a call signature of
```python
def model(weights = None, S = 5, p_ratio = [1.0, 2.6, 2.6, 1.0])
```
as seen on line 22 in `models.py`. If you don't pass any parameters, then `weights` will default to be `None and then on lines 49-50:
```python
if weights:
        model.load_weights(weights)
```
It will not try loading any existing weights into your model.

**Comment by drewgash** [comment]
Thanks Bart. So far so good. One question please, is it possible to continue training from a particular epoch? It takes a lifetime to complete on my laptop.

**Comment by bartchr808** [comment]
I'm pretty rusty with Keras at the moment since I haven't worked with it in a while, but it should be saving your weights to a file called `weights.h5` at the end of every epoch assuming your model after the new epoch has a higher accuracy on the testing data set. Look into using [AWS EC2 P2/P3 Instances](https://aws.amazon.com/ec2/instance-types/) for training instead of using your laptop since it will take a lot less time to train your model.

**Comment by bartchr808** [comment]
Closed issue since original question has been solved. @drewgash feel free to open up a seperate issue if you are having trouble.

**Comment by drewgash** [comment]
Many thanks.
